// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD520WoAsR0NU834TEEhAL7MMz0VxwPaFw',
    appId: '1:829916534757:web:ca14baddc2f56dcc8a010c',
    messagingSenderId: '829916534757',
    projectId: 'stepz-attendance-prod',
    authDomain: 'stepz-attendance-prod.firebaseapp.com',
    storageBucket: 'stepz-attendance-prod.firebasestorage.app',
    measurementId: 'G-ZZPF4D3PSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWflXmui8jSfFZo64LXvqVrM4RAPCfA-E',
    appId: '1:829916534757:android:d0a89c80576a62ef8a010c',
    messagingSenderId: '829916534757',
    projectId: 'stepz-attendance-prod',
    storageBucket: 'stepz-attendance-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG_Ps_PrvuiqYd6izUkXka7-UK44CnZKA',
    appId: '1:829916534757:ios:f11c18b305d713538a010c',
    messagingSenderId: '829916534757',
    projectId: 'stepz-attendance-prod',
    storageBucket: 'stepz-attendance-prod.firebasestorage.app',
    iosBundleId: 'com.stepz.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG_Ps_PrvuiqYd6izUkXka7-UK44CnZKA',
    appId: '1:829916534757:ios:829e84a0d08c306f8a010c',
    messagingSenderId: '829916534757',
    projectId: 'stepz-attendance-prod',
    storageBucket: 'stepz-attendance-prod.firebasestorage.app',
    iosBundleId: 'com.example.stepzAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD520WoAsR0NU834TEEhAL7MMz0VxwPaFw',
    appId: '1:829916534757:web:2252540ae1f8b3e68a010c',
    messagingSenderId: '829916534757',
    projectId: 'stepz-attendance-prod',
    authDomain: 'stepz-attendance-prod.firebaseapp.com',
    storageBucket: 'stepz-attendance-prod.firebasestorage.app',
    measurementId: 'G-LPLNKBD6R9',
  );
}